# Site Info
site_name: hissw
site_description: Run SSW IDL code in Python
site_author: Will Barnes
site_url: 'https://wtbarnes.github.io/hissw'

# Repository
repo_name: wtbarnes/hissw
repo_url: https://github.com/wtbarnes/hissw

# Navigation
nav:
- Getting Started: index.md
- Examples:
    - 'Simple Example' : 'examples/simple_example.md'
    - 'AIA Response Functions' : 'examples/aia_example.md'

theme:
  name: 'material'
  palette:
    primary: 'orange'
    accent: 'yellow'
  icon:
    logo: 'fontawesome/solid/code'

# Extensions
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

# Social/Contact
extra:
  social:
    - icon: 'fontawesome/solid/globe'
      link: 'https://wtbarnes.github.io/'
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/wtbarnes'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/wtbarnes_'
