name: Deploy Docs
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install
        run: |
          pip install .[docs]
      - name: Build Docs
        run: |
          mkdocs build -d site
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: site